apiVersion: v1
kind: Service
metadata:
  labels:
    app: klostra-frontend
  name: klostra-frontend-service
  namespace: frontend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 5000
  selector:
    app: klostra-frontend
